
CREATE TABLE "Person" (
	"Row"	INTEGER NOT NULL,
	"Id"	TEXT NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Age"	INTEGER NOT NULL,
	"Birthday"	TEXT NOT NULL,
	"Remark"	TEXT,
	CONSTRAINT "UNIQUE_Person_Id" UNIQUE("Id"),
	CONSTRAINT "PK_Person" PRIMARY KEY("Row" AUTOINCREMENT)
)

CREATE TABLE "Address" (
	"Row"	INTEGER NOT NULL,
	"Id"	TEXT NOT NULL,
	"Text"	TEXT NOT NULL,
	CONSTRAINT "PK_Address" PRIMARY KEY("Row" AUTOINCREMENT),
	CONSTRAINT "FK_Address_Id" FOREIGN KEY("Id") REFERENCES Person(Id)
		ON UPDATE CASCADE 
		ON DELETE CASCADE
)

INSERT INTO [Person]
([Id],[Name],[Age],[Birthday],[Remark])
VALUES
('A123456789','AAA',18,'2021-01-01',''),
('B123456789','BBB',28,'2021-01-01','')

INSERT INTO [Address]
([Id],[Text])
VALUES
('A123456789','A1'),
('A123456789','A2'),
('B123456789','B1'),
('B123456789','B2')
